In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
import pickle
with open('data.pickle','rb') as read_file:
    df = pickle.load(read_file)

In [28]:
djia_data_2 = pd.read_csv('DIA_index.csv')

In [30]:
djia_data_2['Predicted'] = y_test_pre

In [33]:
money = 2000
prev = -1
num_stock = 1

for i in range(0, len(djia_data_2)): 
#     inital_stock = money / 17823
    if djia_data_2.loc[i,'Predicted'] == prev:
        continue
    elif djia_data_2.loc[i,'Predicted'] != prev:
        if djia_data_2.loc[i,'Predicted'] == 0:     
            money = djia_data_2.loc[i,'Adj Close'] * num_stock
            prev = djia_data_2.loc[i,'Predicted']         
        if djia_data_2.loc[i,'Predicted'] == 1:
            num_stock = money / djia_data_2.loc[i,'Adj Close']
            prev = djia_data_2.loc[i,'Predicted']

In [34]:
money

3175.538803934068

In [37]:
df_test.head()

0         1         2         3         4         5         6  \
0  0.192015 -0.014492  0.069302  0.132442  0.003927  0.045849 -0.118786   
1  0.070369 -0.024457  0.033717 -0.192162  0.149033  0.084145 -0.024440   
2 -0.000521 -0.098438 -0.106019  0.090017 -0.038098  0.356577  0.028341   
3  0.063446 -0.118456 -0.081942 -0.014692  0.012867 -0.101457 -0.078922   
4 -0.163115 -0.055939 -0.005450 -0.077413 -0.008766  0.045063  0.182410   

          7         8         9  lag1  lag2  lag3  
0  0.082788  0.165037  0.095835   1.0   1.0   0.0  
1  0.411624 -0.314850 -0.079474   0.0   1.0   1.0  
2  0.321434 -0.049653  0.240879   1.0   1.0   0.0  
3 -0.091120  0.087616 -0.085515   1.0   0.0   0.0  
4  0.178065  0.297217  0.070074   0.0   0.0   0.0

In [3]:
#######################
# standard code block #
#######################

# see https://ipython.readthedocs.io/en/stable/interactive/magics.html
%pylab inline

# sets backend to render higher res images
%config InlineBackend.figure_formats = ['retina']

#######################
#       imports       #
#######################
import pandas as pd
import seaborn as sns
import sklearn

sns.set_style("whitegrid")

Populating the interactive namespace from numpy and matplotlib


In [4]:
train = df[df['Date'] < '2015-01-01']
test = df[df['Date'] > '2014-12-31']

In [5]:
cv = CountVectorizer(stop_words='english')

X_fit = cv.fit(train['text'])
X_transform = X_fit.transform(train['text'])
X_test = X_fit.transform(test['text'])
y_test = test['Label']
df_train = pd.DataFrame(X_transform.toarray(), columns=cv.get_feature_names())
df_train.shape

(1611, 29726)

In [6]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=5, n_iter=100, random_state=42)
svd_fit = svd.fit(X_transform)  
svd_transform = svd_fit.transform(X_transform)
svd_transform_test = svd_fit.transform(X_test)

In [7]:
svd_transform_test

array([[10.0021102 ,  0.97925018,  0.63459904,  1.16009031,  0.08101788],
       [ 8.92022479,  0.835194  ,  0.18123749, -3.05109767,  2.07960378],
       [ 8.28974237, -0.23426188, -1.59900583,  0.60969081, -0.49779374],
       ...,
       [ 5.24672137, -0.65698395, -1.66507412, -1.26809021, -0.17169268],
       [ 8.23596771,  0.5789071 ,  0.30872772,  0.17698137, -1.71190342],
       [ 9.80173606, -0.13760622, -1.55747546,  0.66972657, -2.596881  ]])

In [8]:
svd_transform

array([[10.40851927,  4.28823476,  5.82880248, -0.44715637,  2.30657461],
       [ 8.16196103,  5.05806067,  6.9437094 ,  3.20926063, -1.42774366],
       [ 8.27953992,  4.99211138,  6.1630044 ,  3.97691677, -0.88806757],
       ...,
       [ 7.36870786,  1.89830138,  0.98665995, -0.59882602,  0.97432039],
       [ 6.61860955,  1.52311707, -1.40105135, -2.26456217,  1.62324523],
       [ 8.42087406,  1.76306941, -0.58732829,  5.37007707,  2.08130096]])

In [9]:
df_train_svd = pd.DataFrame(svd_transform)

In [10]:
df_test_svd = pd.DataFrame(svd_transform_test)

## Normalize data

In [11]:
import pickle
with open('data_train.pickle','rb') as read_file:
    df_train = pickle.load(read_file)

In [12]:
import pickle
with open('data_train_y.pickle','rb') as read_file:
    df_train_y = pickle.load(read_file)

In [13]:
import pickle
with open('data_test.pickle','rb') as read_file:
    df_test = pickle.load(read_file)

In [14]:
import pickle
with open('data_test_y.pickle','rb') as read_file:
    df_test_y = pickle.load(read_file)

In [ ]:
df_train.iloc[:,0:10] = (df_train.iloc[:,0:10] - df_train.iloc[:,0:10].mean()) / (df_train.iloc[:,0:10].max() - df_train.iloc[:,0:10].min())
df_test.iloc[:,0:10] = (df_test.iloc[:,0:10] - df_test.iloc[:,0:10].mean()) / (df_test.iloc[:,0:10].max() - df_test.iloc[:,0:10].min())


In [18]:
svd_transform = np.array(df_train)

In [19]:
svd_transform_test = np.array(df_test)

In [21]:
y = np.array(df_train_y)

In [23]:
svd_transform.shape
# y.shape

(1611, 13)

In [24]:
from sklearn.neural_network import MLPClassifier
# X = [[0., 0.], [1., 1.]]
# y = [0, 1]
clf = MLPClassifier(solver='sgd', alpha=0.0001, activation = 'tanh',batch_size = 3,
                     hidden_layer_sizes=(100, 100, 100),  verbose=10,  tol=0.000000001, random_state=42)

clf.fit(svd_transform, y) 

/Users/zhaoze/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:916: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.67486950
Iteration 2, loss = 0.66693641
Iteration 3, loss = 0.66656787
Iteration 4, loss = 0.66784326
Iteration 5, loss = 0.66743422
Iteration 6, loss = 0.66536538
Iteration 7, loss = 0.66592070
Iteration 8, loss = 0.66472120
Iteration 9, loss = 0.66458938
Iteration 10, loss = 0.66269931
Iteration 11, loss = 0.66541202
Iteration 12, loss = 0.66361637
Iteration 13, loss = 0.66409564
Iteration 14, loss = 0.66480023
Iteration 15, loss = 0.66316334
Iteration 16, loss = 0.66450680
Iteration 17, loss = 0.66230398
Iteration 18, loss = 0.66399555
Iteration 19, loss = 0.66365219
Iteration 20, loss = 0.66302868
Iteration 21, loss = 0.66440596
Iteration 22, loss = 0.66421506
Iteration 23, loss = 0.66261625
Iteration 24, loss = 0.66293611
Iteration 25, loss = 0.66359773
Iteration 26, loss = 0.66189281
Iteration 27, loss = 0.66449242
Iteration 28, loss = 0.66341508
Iteration 29, loss = 0.66268862
Iteration 30, loss = 0.66327736
Iteration 31, loss = 0.66111965
Iteration 32, los

MLPClassifier(activation='tanh', alpha=0.0001, batch_size=3, beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 100, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=42, shuffle=True, solver='sgd', tol=1e-09,
       validation_fraction=0.1, verbose=10, warm_start=False)

In [25]:
y_test_pre = clf.predict(svd_transform_test)

In [26]:
y_test_pre

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [27]:
pd.crosstab(df_test_y, y_test_pre, colnames=["Predicted"], rownames=["Actual"] )

Predicted   0    1
Actual            
0          95   91
1          74  118

### Prediction Accuracy is 56%!

In [22]:
# from sklearn import kernel_approximation
# import keras
# from keras.layers import Activation, Dense

# N_COMP = 10

# x = df_norm.values

# kernel_approx = kernel_approximation.Nystroem(n_components=N_COMP, gamma=2)

# x_rbf_pre = kernel_approx.fit(x)
# x_rbf = x_rbf_pre.transform(x)

# # svm_keras = keras.Sequential([keras.layers.Dense(units=3, input_shape=(N_COMP, )), keras.layers.Dense(units=1,activation='tanh')])

# keras.initializers.glorot_uniform(seed=None)
# svm_keras = keras.Sequential()

# svm_keras.add(Dense(output_dim=500, input_shape=(N_COMP, )))
# svm_keras.add(Activation("relu"))
# svm_keras.add(Dense(output_dim=1))
# svm_keras.add(Activation("tanh"))

# # model = keras.Sequential([
# #     keras.layers.Flatten(input_shape=(28, 28)),
# #     keras.layers.Dense(128, activation=tf.nn.relu),
# #     keras.layers.Dense(10, activation=tf.nn.softmax)
# # ])

# # svm_keras = keras.Sequential(
# #     [keras.layers.Dense(units=50, activation='relu', input_shape=(N_COMP, )),
# #      keras.layers.Dense(units=30, activation='relu'),
# #     keras.layers.Dense(units=1,activation='tanh')])

# svm_keras.compile(optimizer="sgd", loss="categorical_hinge")

# svm_keras_fit = svm_keras.fit(x=x_rbf, y=train["Label"], batch_size= 5 , epochs=20)

In [23]:
# X_test_cv = X_fit.transform(test['text'])
# X_test_svd = svd_fit.transform(X_test_cv)
# df_test_svd = pd.DataFrame(X_test_svd)